- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/{{ deploy_user }}/.ssh
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0700'

- name: Check if authorized key is present
  stat:
    path: /home/{{ deploy_user }}/.ssh/authorized_keys
  register: ssh_key_check

- name: Add authorized key
  ansible.builtin.copy:
    dest: /home/{{ deploy_user }}/.ssh/authorized_keys
    content: "{{ deploy_user_ssh_public_key }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0600'
  when: ssh_key_check.stat.exists == false
