- hosts: webservers
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Create non-root user
      include_role:
        name: common

- hosts: webservers
  become: true
  become_user: "{{ deploy_user }}"
  vars_files:
    - vars.yml
  tasks:
    - name: Setup SSH for non-root user
      include_role:
        name: ssh

    - name: Install and configure Nginx
      include_role:
        name: nginx

    - name: Install Certbot and obtain SSL certificates
      include_role:
        name: certbot

    - name: Install WireGuard and configure client
      include_role:
        name: wireguard

    - name: Install Docker
      include_role:
        name: docker

    - name: Install Node.js 22
      include_role:
        name: node

    - name: Install Yarn
      include_role:
        name: yarn
