- name: Check if Yarn is installed
  ansible.builtin.command: yarn --version
  register: yarn_installed
  ignore_errors: true
  become: true
  become_user: root

- name: Install Yarn using npm
  ansible.builtin.command: npm install -g yarn
  when: yarn_installed.rc != 0
  become: true
  become_user: root
