# WireGuard Configuration
wireguard_client_private_key_path: "/etc/wireguard/wireguard_client_private_key"
wireguard_client_public_key_path: "/etc/wireguard/wireguard_client_public_key"
wireguard_client_config_path: "/etc/wireguard/wg0-client.conf"
wireguard_client_ip: "10.0.0.12"
wireguard_dns: "8.8.8.8"
wireguard_server_public_key: "j5EVvv+7wb7QQMJyz8KuX4PJKoux1dRJHuc+D6rmkwg="
wireguard_client_private_key: "MNgI2DQnGv0P59I6vlbrd+CE7xbemGOb72afhg2NXGk="
wireguard_server_endpoint: "178.208.75.8:51820"

# User Configuration
deploy_user: "deployuser"
deploy_user_password: "s2_7salc<mcsVU13"
deploy_user_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCofCrojdolSWpR0L/LHJr2u+Pamf/0KQLjg5HtLwo9N/u8t5iExL/y9kfgu1gpVAKAv7ZWkD1LBC6YXQ6bpY/TTnp7OBg2O4nXr6/I9tK1uJtpFsFcj3pYFUteKcxZr+MHuFOmysjg7HRbufrSOh74Dp1R8rOU04TD3oyj/xBuDbnS5Tz/dk1048USD39y7CL97VZHQr46/Ipzc20mNDG9P8stEyxFhuT0SaFOUpYn3AFMEQDIxHhGdNWzi4Kagpw6HRu8ejcSZRdI5al69DzOOFj7SuItddvoivnCcO42V/geMtD68btvVmwydG7S6KT/jvtkIv6q27rN5R9x/lGR gaever@MacBook-Pro.local"


# Ports Configuration
frontend_port: 3000
graphql_port: 8080
sso_port: 9080

# Email for Let's Encrypt
letsencrypt_email: "mail@godigital.team"  # Email для регистрации Let's Encrypt

# Domain Configuration
project_domain: "godigital.team"
frontend_subdomain: "tgstat"
graphql_subdomain: "graphql"
sso_subdomain: "sso"

# Hasura configuration
hasura_cli_version: v2.38.0