- name: Create Nginx configuration for frontend with SSL
  ansible.builtin.template:
    src: templates/nginx_with_ssl.conf.j2
    dest: /etc/nginx/sites-enabled/{{ frontend_subdomain | default('') ~ (frontend_subdomain | length > 0) | ternary('.', '') }}{{ project_domain }}
  notify: reload nginx

- name: Create Nginx configuration for graphql with SSL
  ansible.builtin.template:
    src: templates/graphql_with_ssl.conf.j2
    dest: /etc/nginx/sites-enabled/{{ graphql_subdomain | default('') ~ (graphql_subdomain | length > 0) | ternary('.', '') }}{{ project_domain }}
  notify: reload nginx

- name: Create Nginx configuration for sso with SSL
  ansible.builtin.template:
    src: templates/nginx_with_ssl.conf.j2
    dest: /etc/nginx/sites-enabled/{{ sso_subdomain | default('') ~ (sso_subdomain | length > 0) | ternary('.', '') }}{{ project_domain }}
  notify: reload nginx

- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
  become: true
  become_user: root

- name: Test Nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  register: nginx_test_result
  ignore_errors: true
  become: true
  become_user: root

- name: Fail if Nginx configuration is invalid
  ansible.builtin.fail:
    msg: "Nginx configuration is invalid"
  when: nginx_test_result.rc != 0
