- hosts: webservers
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Clone or update repositories
      shell: |
        if cd {{ base_dir }}/{{ item.name }}; then
          git reset --hard && git clean -fd && git checkout main && git pull;;
        else
          git clone {{ item.url }} {{ base_dir }}/{{ item.name }};
        fi
      with_items: "{{ repositories }}"
      remote_user: "{{ remote_user }}"
